/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{child_id}/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weeks
         * @description Week starts with data, newest first.
         */
        get: operations["weeks_children__child_id__weeks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{child_id}/weeks/{week_start}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week */
        get: operations["week_children__child_id__weeks__week_start__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourlyTopicCount */
        HourlyTopicCount: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Hour */
            hour: number;
            /**
             * Topic
             * @enum {string}
             */
            topic: "loneliness" | "sadness" | "stress" | "anxiety" | "anger" | "self_worth" | "school" | "friends" | "family" | "romance" | "body_image" | "boredom" | "other";
            /** Count */
            count: number;
        };
        /** SiteAggregate */
        SiteAggregate: {
            /**
             * Site
             * @enum {string}
             */
            site: "chatgpt" | "claude" | "characterai" | "gemini";
            /**
             * Level
             * @enum {string}
             */
            level: "healthy" | "watch" | "concerning" | "crisis";
            /** Score */
            score: number;
            /** Active Minutes */
            active_minutes: number;
            /** Late Night Sessions */
            late_night_sessions: number;
            /**
             * Voice Minutes
             * @default 0
             */
            voice_minutes: number;
            /** Nudges Shown */
            nudges_shown: number;
            /** Paid Tier */
            paid_tier?: boolean | null;
        };
        /** SyncPayload */
        SyncPayload: {
            /** Child Id */
            child_id: string;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Sites */
            sites: components["schemas"]["SiteAggregate"][];
            /** Hourly Topics */
            hourly_topics: components["schemas"]["HourlyTopicCount"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sync_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weeks_children__child_id__weeks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_children__child_id__weeks__week_start__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: string;
                week_start: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
