/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extra Session
         * @description The extension picks up the dashboard's login in the same browser: it trades the dashboard's
         *     token for its own (extension/src/content/dashboard.ts).
         */
        post: operations["extra_session_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{child_id}/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weeks
         * @description Week starts with data, newest first.
         */
        get: operations["weeks_children__child_id__weeks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{child_id}/weeks/{week_start}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week */
        get: operations["week_children__child_id__weeks__week_start__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/children/{child_id}/weeks/{week_start}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Topics
         * @description Per-topic counts this week vs last week, most frequent first.
         */
        get: operations["topics_children__child_id__weeks__week_start__topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ratings */
        get: operations["ratings_tools_ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/starters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Starters */
        get: operations["list_starters_starters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourlyTopicCount */
        HourlyTopicCount: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Hour */
            hour: number;
            /**
             * Topic
             * @enum {string}
             */
            topic: "loneliness" | "sadness" | "stress" | "anxiety" | "anger" | "self_worth" | "hopelessness" | "emptiness" | "rejection" | "guilt_shame" | "overwhelm" | "fear" | "grief" | "jealousy" | "frustration" | "happiness" | "school" | "friends" | "family" | "romance" | "body_image" | "boredom" | "other";
            /** Count */
            count: number;
        };
        /** LoginResult */
        LoginResult: {
            /** Token */
            token: string;
            /** Email */
            email: string;
        };
        /** Me */
        Me: {
            /** Email */
            email: string;
        };
        /** SiteAggregate */
        SiteAggregate: {
            /**
             * Site
             * @enum {string}
             */
            site: "chatgpt" | "claude" | "characterai" | "gemini";
            /**
             * Level
             * @enum {string}
             */
            level: "healthy" | "watch" | "concerning" | "crisis";
            /** Score */
            score: number;
            /** Active Minutes */
            active_minutes: number;
            /** Late Night Sessions */
            late_night_sessions: number;
            /**
             * Voice Minutes
             * @default 0
             */
            voice_minutes: number;
            /** Nudges Shown */
            nudges_shown: number;
            /**
             * Privacy Pauses
             * @default 0
             */
            privacy_pauses: number;
            /** Paid Tier */
            paid_tier?: boolean | null;
        };
        /**
         * Starter
         * @description Vetted conversation starter (desc.md feature 2). `topic` is a Topic or "default".
         */
        Starter: {
            /** Topic */
            topic: ("loneliness" | "sadness" | "stress" | "anxiety" | "anger" | "self_worth" | "hopelessness" | "emptiness" | "rejection" | "guilt_shame" | "overwhelm" | "fear" | "grief" | "jealousy" | "frustration" | "happiness" | "school" | "friends" | "family" | "romance" | "body_image" | "boredom" | "other") | "default";
            /** Text */
            text: string;
        };
        /**
         * SyncPayload
         * @description One device's week. Several devices (browsers) can report for the same child_id.
         */
        SyncPayload: {
            /** Child Id */
            child_id: string;
            /**
             * Device Id
             * @default legacy
             */
            device_id: string;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Sites */
            sites: components["schemas"]["SiteAggregate"][];
            /** Hourly Topics */
            hourly_topics: components["schemas"]["HourlyTopicCount"][];
        };
        /**
         * ToolRating
         * @description Hand-curated rating for one AI site (desc.md feature 6). Stored in MongoDB, never generated.
         */
        ToolRating: {
            /**
             * Site
             * @enum {string}
             */
            site: "chatgpt" | "claude" | "characterai" | "gemini";
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "general_assistant" | "companion";
            /** Min Age */
            min_age: number;
            /** Teen Safety Settings */
            teen_safety_settings: boolean;
            /** Summary */
            summary: string;
            /** Recommendation */
            recommendation: string;
        };
        /**
         * TopicTrend
         * @description Per-topic counts for one week vs the week before (computed by a MongoDB aggregation).
         */
        TopicTrend: {
            /**
             * Topic
             * @enum {string}
             */
            topic: "loneliness" | "sadness" | "stress" | "anxiety" | "anger" | "self_worth" | "hopelessness" | "emptiness" | "rejection" | "guilt_shame" | "overwhelm" | "fear" | "grief" | "jealousy" | "frustration" | "happiness" | "school" | "friends" | "family" | "romance" | "body_image" | "boredom" | "other";
            /** This Week */
            this_week: number;
            /** Last Week */
            last_week: number;
            /** Late Night */
            late_night: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeekSummary
         * @description A child's week as the parent sees it: every device added up (api/db.py load_week).
         */
        WeekSummary: {
            /** Child Id */
            child_id: string;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Devices */
            devices: number;
            /** Sites */
            sites: components["schemas"]["SiteAggregate"][];
            /** Hourly Topics */
            hourly_topics: components["schemas"]["HourlyTopicCount"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    extra_session_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    sync_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weeks_children__child_id__weeks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_children__child_id__weeks__week_start__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: string;
                week_start: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_children__child_id__weeks__week_start__topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child_id: string;
                week_start: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicTrend"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ratings_tools_ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolRating"][];
                };
            };
        };
    };
    list_starters_starters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Starter"][];
                };
            };
        };
    };
}
